### ISSUE TITLE
Add \( and \) support

### ISSUE THREAD

**Issue by hemashushu** [waylonflinn/markdown-it-katex#10]
For render the inline equation that enclose with \\( and \\), and the block equation that enclose with \\[ and \\], thanks!

**Comment by zackw** [comment]
This has a high risk of conflicting with Markdown's other uses for [ ] ( ).  If it is implemented, please make it possible to turn it off.

**Comment by laygir** [comment]
came here for the same thing. I'm trying to display math expressions from GPT but failing to render inline expression as `\(` and `\)` is not supported, any workaround or I patch I can apply my self?

**Comment by Rrojaski** [comment]
Was there a workaround for this found or maybe a parameter I can pass to allow the delimiters \( ... \) and \[ ... \]?
