### ISSUE TITLE
could not parse  xxx$-2x<4$xxx

### ISSUE THREAD

**Issue by xiaokaike** [waylonflinn/markdown-it-katex#2]
```text
xxx$-2x<4$xxx
```
![image](https://cloud.githubusercontent.com/assets/4251499/14484207/f122f78a-0180-11e6-9b6d-6ee6feb404e9.png)

**Comment by waylonflinn** [comment]
Thanks for the bug report!

**Comment by waylonflinn** [comment]
fixed with #3
