### ISSUE TITLE
Space after $ causes line not to render

### ISSUE THREAD

**Issue by eoinmurray** [waylonflinn/markdown-it-katex#8]
For example:

$\alpha$ renders fine.

But $ \alpha$ with a space doesn't render into math, just stays as the string

**Comment by eoinmurray** [comment]
Not true - it must be an error on my side, not with the library

**Comment by waylonflinn** [comment]
Thanks for reporting this. I know you've closed it, but I still want to try to reproduce the error on my end. If I'm able to, I'll post an update here.
